In [11]:
import pandas as pd

In [13]:
df = [{'Fellowship_ID':1001,'FirstName':'Frodo','Skills':'Hiding'},{'Fellowship_ID':1002,'FirstName':'Samwise','Skills':'Gardening'},{'Fellowship_ID':1003,'FirstName':'Gandalf','Skills':'Spells'},{'Fellowship_ID':1004,'FirstName':'Pippin','Skills':'Fireworks'}]
df

[{'Fellowship_ID': 1001, 'FirstName': 'Frodo', 'Skills': 'Hiding'},
 {'Fellowship_ID': 1002, 'FirstName': 'Samwise', 'Skills': 'Gardening'},
 {'Fellowship_ID': 1003, 'FirstName': 'Gandalf', 'Skills': 'Spells'},
 {'Fellowship_ID': 1004, 'FirstName': 'Pippin', 'Skills': 'Fireworks'}]

In [14]:
df1 =pd.DataFrame(df)
df1

   Fellowship_ID FirstName     Skills
0           1001     Frodo     Hiding
1           1002   Samwise  Gardening
2           1003   Gandalf     Spells
3           1004    Pippin  Fireworks

In [15]:
df = [{'Fellowship_ID':1001,'FirstName':'Frodo','Age':50},{'Fellowship_ID':1002,'FirstName':'Samwise','Age':39},{'Fellowship_ID':1006,'FirstName':'Legolas','Age':2931},{'Fellowship_ID':1007,'FirstName':'Elrond','Age':6520},{'Fellowship_ID':1008,'FirstName':'Barromir','Age':51}]
df2 = pd.DataFrame(df)
df2

   Fellowship_ID FirstName   Age
0           1001     Frodo    50
1           1002   Samwise    39
2           1006   Legolas  2931
3           1007    Elrond  6520
4           1008  Barromir    51